loom.mixin.useLegacyMixinAp=false
loom.platform=neoforge

minecraft_version=1.21.1
neo_forge_version=21.1.234
architectury_version=13.0.8
hexcasting_version=0.12.0-devel-pre-39
inline_version=1.2.2
cloth_config_version=15.0.130
patchouli_version=1.21.1-93-NEOFORGE
paucal_version=0.7.1-pre-27
caelus_version=7.0.1+1.21.1
forge_kotlin_version=5.12.0
modid=hexxytounge
mod_version=0.1.0-neoforge-probe
archives_base_name=hexxytounge
maven_group=org.eu.net.pool
